### ISSUE TITLE
Disable the single page.

### ISSUE THREAD

**Issue by caiotarifa** [ibrado/jekyll-paginate-content#3]
There is a way to disable the creation of the single page?

**Comment by ibrado** [comment]
Hmmm. I've not tried it yet, but I think this will work:

```
paginate_content:
  properties:
    single:
       published: false
```

Let me know if it works...
